WITH CTE AS (
    SELECT
    TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

    CASE
    WHEN DAYNAME(TO_TIMESTAMP(STARTED_AT)) IN ('Sat','Sun')
    THEN 'WEEKEND'
    ELSE 'BUSSINESSDAY'
    END AS DAYTYPE,

    CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (12,1,2)
        THEN 'WINTER'
        WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (3,4,5)
        THEN 'SPRING'
        WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (6,7,8)
        THEN 'SUMMER'
        ELSE 'AUTUMN'
        END AS SEASON_OF_THE_YEAR

    FROM {{ source('demo', 'bike') }}
    WHERE STARTED_AT != 'started_at'
)

select * from CTE